networks:
  default:
    name: upgrading_protocol_version

volumes:
  postgres:
    name: canton_postgres

services:

  canton_postgres:
    image: postgres:14.10
    container_name: canton-postgres
    profiles:
      - "startup"
      - "all"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./configs/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 1
    expose:
      - 5432
    ports:
      - 5432:5432
  
  # Original domain and participants

  olddomain:
    container_name: olddomain
    profiles:
      - "startup"
      - "all"
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.3.20
    volumes:
      - ./configs:/canton/host/configs:r
    command: daemon --config "/canton/host/configs/domains/domain.conf" --log-profile container --log-level-root INFO
    depends_on:
      canton_postgres:
        condition: service_healthy
    expose:
      - 5001
      - 5002
    ports:
      - 5001:5001
      - 5002:5002

  participantb:
    container_name: participantb
    profiles:
      - "startup"
      - "all"
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.3.20
    volumes:
      - ./configs:/canton/host/configs:r
      - ./.daml/dist/:/canton/host/dist/:r
    command: daemon --config "/canton/host/configs/participants/participantb.conf" --bootstrap "/canton/host/configs/participants/participantb.canton" --log-profile container --log-level-root INFO
    depends_on:
      olddomain:
        condition: service_started
      canton_postgres:
        condition: service_healthy
    expose:
      - 5005
      - 5006
    ports:
      - 5005:5005
      - 5006:5006

  participanta:
    container_name: participanta
    profiles:
      - "startup"
      - "all"
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.3.20
    volumes:
      - ./configs:/canton/host/configs:r
      - ./.daml/dist/:/canton/host/dist/:r
    command: daemon --config "/canton/host/configs/participants/participanta.conf" --bootstrap "/canton/host/configs/participants/participanta.canton" --log-profile container --log-level-root INFO
    depends_on:
      olddomain:
        condition: service_started
      canton_postgres:
        condition: service_healthy
    expose:
      - 5007
      - 5008
    ports:
      - 5007:5007
      - 5008:5008

  # New domain and participants with updated binaries

  newdomain:
    container_name: newdomain
    profiles:
      - "new-domain"
      - "all"
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.9.1
    volumes:
      - ./configs:/canton/host/configs:r
    command: daemon --config "/canton/host/configs/domains/newdomain.conf" --log-profile container --log-level-root INFO
    expose:
      - 5003
      - 5004
    ports:
      - 5003:5003
      - 5004:5004

  participanta_new:
    container_name: participanta
    profiles:
      - "updated-participants"
      - "all"
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.9.1
    volumes:
      - ./configs:/canton/host/configs:r
      - ./.daml/dist/:/canton/host/dist/:r
    command: daemon --config "/canton/host/configs/participants/newparticipanta.conf" --log-profile container --log-level-root Info --manual-start
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/grpc_health_probe",
          "--addr",
          "participanta:5861"
        ]
    expose:
      - 5007
      - 5008
    ports:
      - 5007:5007
      - 5008:5008

  participantb_new:
    container_name: participantb
    profiles:
      - "updated-participants"
      - "all"
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.9.1
    volumes:
      - ./configs:/canton/host/configs:r
      - ./.daml/dist/:/canton/host/dist/:r
    command: daemon --config "/canton/host/configs/participants/newparticipantb.conf" --log-profile container --log-level-root INFO --manual-start
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/grpc_health_probe",
          "--addr",
          "participantb:5861"
        ]
    expose:
      - 5005
      - 5006
    ports:
      - 5005:5005
      - 5006:5006

  # Helpers

  console:
    container_name: console
    profiles:
      - "all"
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.9.1
    volumes:
      - ./:/canton/host/:rw
    command:
      - --no-tty
      - -c=/canton/host/configs/remote/remote.conf
  
  startup:
    container_name: startup
    profiles:
      - "startup"
      - "all"
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.3.20
    volumes:
      - ./configs:/canton/host/configs:rw
    command: run /canton/host/configs/remote/setup.canton --config "/canton/host/configs/remote/remote.conf" --log-profile container --log-level-root INFO
    depends_on:
      participantb:
        condition: service_started
      participanta:
        condition: service_started

  remove_resources:
    container_name: remove_resources
    profiles:
      - "all"
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.9.1
    volumes:
      - ./configs:/canton/host/configs:rw
      - ./canton-scripts:/canton/host/canton-scripts:r
    command: run /canton/host/canton-scripts/remove-resources.canton --config "/canton/host/configs/remote/remote.conf" --log-profile container --log-level-root INFO
  
  restore_and_test:
    container_name: restore_aand_test
    profiles:
      - "all"
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.9.1
    volumes:
      - ./configs:/canton/host/configs:rw
      - ./canton-scripts:/canton/host/canton-scripts:r
    command: run /canton/host/canton-scripts/restore-resources-and-test.canton --config "/canton/host/configs/remote/remote.conf" --log-profile container --log-level-root INFO

  migrate:
    container_name: migrate
    profiles:
      - "all"
    image: digitalasset-docker.jfrog.io/canton-enterprise:2.9.1
    environment:
      - OLD_DOMAIN=olddomain
      - NEW_DOMAIN=newdomain
      - NEW_DOMAIN_ADDRESS=http://newdomain:5003
    volumes:
      - ./configs:/canton/host/configs:rw
      - ./canton-scripts:/canton/host/canton-scripts:r
    command: run /canton/host/canton-scripts/migrate.canton --config "/canton/host/configs/remote/remote.conf" --log-profile container --log-level-root INFO

  contracts:
    container_name: contracts
    profiles:
      - "all"
    image: digitalasset-docker.jfrog.io/daml-script:2.9.1
    volumes:
      - ./configs:/canton/host/configs:r
      - ./.daml/dist/:/canton/host/dist/:r
    command: --dar /canton/host/dist/upgrade-pv-demo-0.1.0.dar --script-name Main:setup --participant-config /canton/host/configs/participant-config.json
  